version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend
    ports:
      - '80:3000'
  backend:
    build:
      context: .
      dockerfile: backend
    ports:
      - '1337:8080'

