version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend
    image: zsr2531/checkers-frontend
    ports:
      - '80:3000'
  backend:
    build:
      context: .
      dockerfile: backend
    image: zsr2531/checkers-backend
    ports:
      - '8080:8080'

